### PR TITLE
buildinfo: skip blank lines during parse

### LINKED ISSUE #15: Fails with Go 1.18 again
It appears to be failing on blank lines in the output of `go version -m`. This is the complete output:

```
2022/03/15 12:49:04 failed to evaluate licenses: unrecognised line: 	
```

### PR DESCRIPTION
**Pull request by nick-jones**
Resolves #15

### CODE REVIEW

File: internal/buildinfo/parse.go [hunk 1]
```diff
@@ -73,6 +73,8 @@ func Parse(info string) ([]model.BuildInfo, error) {
 			}
 		case "build":
 			// introduced in Go 1.18 - not captured as we aren't using it for anything
+		case "":
+			// blank (tab pefixed) lines appear after lines relating to replace directives in Go 1.18 compiled binaries
```
Comment (coder543) [inline internal/buildinfo/parse.go:77]:
```suggestion
			// blank (tab prefixed) lines appear after lines relating to replace directives in Go 1.18 compiled binaries
```
